### ISSUE TITLE
YAML parser with custom tags

### ISSUE THREAD

**Issue by jasny** [legalthings/data-enricher#39]
* https://www.php.net/manual/en/yaml.callbacks.parse.php
* https://github.com/dlang-community/D-YAML/wiki/Custom-YAML-data-types

Example;
```yaml
{
  foo: !ref abc
  bar: !tpl hello {{ planet }}
}
```
